#!/usr/bin/env bash

set -euo pipefail

read -p "b for build: " build_path

# -- Choose build_path --
# Normal

if [ "$build_path" = "b" ]; then
	mkdir -p bin
	if gcc -Wall -Wextra -Iinclude -o bin/chell main.c src/chell.c; then
		./bin/chell
	else
		echo "build failed"
	fi
fi


